language: python
sudo: false # use container based infrastructure
jdk: openjdk11
services: postgresql
addons:
  postgresql: 11
dist: bionic
env:
  global:
    - TESTMODEL_URL=http://localhost:8080/intermine-demo
    - TESTMODEL_PATH=intermine-demo
before_script:
  - "./config/travis/init-solr.sh"
  - "./config/travis/init.sh"
script: 
  - python setup.py test
  - python setup.py livetest
python:
  - "3.7"
  - "3.8"
