---
os: linux
language: python
jdk: openjdk11
dist: focal
addons:
  - postgresql: 12.2
services: postgresql
env:
  global:
    - TESTMODEL_URL=http://localhost:8080/intermine-demo
    - TESTMODEL_PATH=intermine-demo
before_script:
  - "./config/travis/init-solr.sh"
  - "./config/travis/init.sh"
script:
  - python setup.py test
  - python setup.py livetest
python:
  - "3.6"
  - "3.7"

