language: python
sudo: false
jdk: openjdk8
dist: bionic
addons:
  - postgresql: 11
services: postgresql
env:
  global:
    - TESTMODEL_URL=http://localhost:8080/intermine-demo
    - TESTMODEL_PATH=intermine-demo
before_script:
  - jdk_switcher use openjdk8
  - java -version
  - javac -version
  - "./config/travis/init-solr.sh"
  - "./config/travis/init.sh"
script:
  - python setup.py test
  - python setup.py livetest
python:
  - "3.7"
  - "3.8"
