---
os: linux
language: python
jdk: openjdk11
dist: bionic
services: postgresql
addons:
  postgresql: 11
env:
  global:
    - TESTMODEL_URL=http://localhost:8080/intermine-demo
    - TESTMODEL_PATH=intermine-demo
before_script:
  - "./config/travis/init-solr.sh"
  - "./config/travis/init.sh"
script:
  - python setup.py test
  - python setup.py livetest
python:
  - "3.6"
  - "3.7"

