language: python
sudo: false
jdk: openjdk8
dist: bionic
addons:
  - postgresql: 11
services: postgresql
env:
  global:
    - TESTMODEL_URL=http://localhost:8080/intermine-demo
    - TESTMODEL_PATH=intermine-demo
script:
  - java -version
  - javac -version
  - echo $JAVA_HOME
  - update-java-alternatives -l
  - jdk_switcher use openjdk8
  - "./config/travis/init-solr.sh"
  - "./config/travis/init.sh"
  - python setup.py test
  - python setup.py livetest
python:
  - "3.7"
  - "3.8"
